language: python
sudo: true

python:
  - "2.7"

addons:
  apt:
    packages:
    - python-dev
    - libxml2-dev
    - libxslt1-dev

virtualenv:
  system_site_packages: true

install:
  - "pip install -r development.txt"
  - "sudo pip install ."

before_script:
  - export PYTHONPATH=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
  - echo $PYTHONPATH
  - python -c 'from jnpr.junos import exception;print exception'

script: 
  nosetests -v --with-coverage --cover-package=jnpr.jsnapy --cover-inclusive -a unit

after_success:
  coveralls

notifications:
  email: false
