language: python
sudo: true

python:
  - "2.7"

addons:
  apt:
    packages:
    - python-dev
    - libxml2-dev
    - libxslt1-dev

virtualenv:
  system_site_packages: true

before_install:
  - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
  - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt 

install:
  - "pip install -r development.txt"
  - "sudo pip install ."

script: 
  nosetests -v --with-coverage --cover-package=jnpr.jsnapy --cover-inclusive -a unit

after_success:
  coveralls

notifications:
  email: false
