# for one device, can be given like this:
hosts:
  - device: 10.221.130.68 
    username: regress 
    passwd: MaRtInI
tests:
  - /Users/ishaank/Desktop/work-jsanpy/jsnapy/samples/test_no_diff.yml 


###################################
# can send mail by specifying:
# mail: send_mail.yml

####################################
